#!/usr/bin/env bash
# configure web-02 to be identical to web-01, add custom header
apt-get update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
new_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/ismakr permanent;"
sudo sed -i "s/server_name _;/$new_str/" /etc/nginx/sites-available/default
cust_str="listen\ \[\:\:\]\:80\ default_server;\n\n\tadd_header\ X-Served-By\ $HOSTNAME;\n"
sudo sed -i "s/listen\ \[\:\:\]\:80\ default_server;/$cust_str/" /etc/nginx/sites-available/default
sudo service nginx restart
