#!/usr/bin/env bash
#Configure HAproxy so that it send traffic to web-01 and web-02
apt-get update
apt-get -y install haproxy
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy
echo -e "\nfrontend myfrontend\n\tbind *:80\n\tmode http\n\tdefault_backend myservers\n\nbackend myservers\n\tbalance roundrobin\n\tserver web-01 100.25.45.81:80 check\n\tserver web-02 100.26.227.36:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
