#!/usr/bin/env bash
# displays Best School 10 times, 9th iteration 
# displays Best School and then Hi on a new line.
x=1
while [ $x -le 10 ]
do
  echo "Best School"
  if [ $x = 9 ]
  then
	  echo "Hi"
  fi
  x=$((x + 1))
done
