#!/usr/bin/env bash
# displays Best School 10 times, 9th iteration 
# displays Best School and then Hi on a new line.
x=1
while [ $x -le 20 ]
do
	echo "$x"
	case $x in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			;;
	esac
	x=$((x + 1))
done
