#!/usr/bin/env bash
# displays Best School 10 times, 9th iteration 
# displays Best School and then Hi on a new line.
h=0
while [ $h -le 12 ]
do
  echo "Hour: $h"
  min=1
  while [ $min -le 59 ]
  do
	echo "$min"
	min=$((min + 1))
  done
  h=$((h + 1))
done
