#!/usr/bin/env bash
# script that gives you information about the school file.
if ! test -f school; then
	echo "school file does not exist"
else
	echo "school file exists"
	if ! test -s school; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f school ]; then
		echo "school is a regular file"
	fi	
fi	
