#!/usr/bin/env bash
# configures an Ubuntu server
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo "facebook.com\t8.8.8.8" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
