#!/usr/bin/env bash
#nginx must be running as nginx user
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf
sudo service nginx restart
